### ISSUE TITLE
error[E0658]: arbitrary expressions in key-value attributes are unstable

### ISSUE THREAD

**Issue by flavv** [fornwall/rust-script#41]
$ cargo install rust-script
    Updating crates.io index
[...]
[...]
   Compiling env_logger v0.9.0
   Compiling clap_derive v3.0.0-beta.5
   Compiling clap v3.0.0-beta.5
error[E0658]: arbitrary expressions in key-value attributes are unstable
 --> /home/flav/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.0.0-beta.5/src/lib.rs:8:10
  |
8 | #![doc = include_str!("../README.md")]
  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #78835 <https://github.com/rust-lang/rust/issues/78835> for more information

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `clap`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `rust-script v0.18.0`, intermediate artifacts can be found at `/tmp/cargo-installAqSpQJ`

Caused by:
  build failed

**Comment by fornwall** [comment]
Hm, seems to be that the latest clap 3 beta requires rust 1.54 (due to [extended_key_value_attributes becoming stable there](https://github.com/rust-lang/rust/pull/83366)) - see https://github.com/clap-rs/clap/issues/2741.

I'm thinking we need to state and bump our MSRV (Minimum Supported Rust Version) to 1.54 - will that be a problem for you, @flavv, or will you be able to update? If possible, using [rustup](https://rustup.rs/) should make updating smooth.

**Comment by fornwall** [comment]
Let's go for 1.54 as minimum supported rust version (MSRV) - I've added that information in the README now.

**Comment by flavv** [comment]
$ rustc --version
rustc 1.57.0 (f1edd0429 2021-11-29)

$ echo 'println!("Hello, World!");' > hello.rs
$ rust-script hello.rs
Hello, World!

it works fine !
